typography_spectrum: 0.453142196405679
color:
  brandStrength: 0.1769518565852195
  lightness: 0.36941766063682735
  saturation: 0.6062385814730078
  rhythmicContrast: 0.4589855393860489
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
layout_spectrum: 0.21111234137788415
author:
  name: Daniel Greenspan
  email: danielg@danielg.com
name: Daniel Greenspan
navigation:
  - name: How to contact us
    id: 662abb1a-b415-4ba4-9bfe-4cfd3c5362a8
    type: content
title: 'Electronics, Computers, Systems'
description: architecture & design consultancy
